[versions]
activityCompose = "1.12.2"
androidDocumentationPlugin = "2.1.0"
espressoCore = "3.7.0"
foundationAndroid = "1.10.0"
junit = "4.13.2"
junitAndroid = "1.3.0"
composeMaterial = "1.13.0"
composeMaterial3 = "1.4.0"
material = "1.10.0"
uiToolingPreview = "1.10.0"
kotlin = "2.3.0"
androidAppPlugin = "8.12.3"
androidLibPlugin = "8.12.3"
composeWear = "1.5.6"
wearToolingPreview = "1.0.0"

[libraries]
android-documentation-plugin = { module = "org.jetbrains.dokka:android-documentation-plugin", version.ref = "androidDocumentationPlugin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-foundation-android = { module = "androidx.compose.foundation:foundation-android", version.ref = "foundationAndroid" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitAndroid" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "material" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiToolingPreview" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "uiToolingPreview" }
junit = { module = "junit:junit", version.ref = "junit" }
material = { module = "com.google.android.material:material", version.ref = "composeMaterial" }
compose-wear-material3 = { group = "androidx.wear.compose", name = "compose-material3", version.ref = "composeWear" }
compose-wear-foundation = { group = "androidx.wear.compose", name = "compose-foundation", version.ref = "composeWear" }
androidx-wear-tooling-preview = { group = "androidx.wear", name = "wear-tooling-preview", version.ref = "wearToolingPreview" }

[plugins]
android-app = { id = "com.android.application", version.ref = "androidAppPlugin" }
android-lib = { id = "com.android.library", version.ref = "androidLibPlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "androidDocumentationPlugin" }
